name: Compilar APK Oficial

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Compilar con Buildozer Action
        uses: ArtemSydoryk/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: 1.5.0

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: EcuBot-APK
          path: bin/*.apk
